[29기 김지연] 장바구니 기능 구현
wecode-bootcamp-korea/29-1st-JU-LABO-backend pull request #10
Opened 2022-02-04 04:10 UTC by jiyeon-kim-ds

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니 기능 (조회, 추가, 수정 삭제) 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. user_id를 통해 장바구니를 조회할 수 있도록 함.
2. `get_or_update()`를 사용하여 장바구니에 상품 추가 및 수정이 가능하도록 함
3. user_id, product_id를 받아 해당 상품을 장바구니에서 삭제하도록 함

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- `get_or_update()` & `update_or_create()` 두 개 모두 사용해 보며 지금 상황에 뭐가 더 적절한 지 확인 할 수 있었다.
- 첫 모델링에서 모자란 부분을 많이 발견하여 모델링 시 좀 더 멀리 볼 수 있게 끔 해야겠다는 생각을 했다.
<br />

## :: 기타 질문 및 특이 사항

2022-02-04 04:25 UTC, cch0807 reviewed
view파일 컨벤션 수정이 전체적으로 필요합니다!

2022-02-04 04:25 UTC, cch0807 commented on users/views.py
> +class CartView(View):
try except문을 사용해서 에러처리가 필요할것같습니다!

2022-02-04 04:25 UTC, cch0807 commented on users/views.py
> +    def get(self, request):
마찬가지로 에러처리가 필요합니다!

2022-02-04 04:25 UTC, cch0807 commented on products/views.py
> +from django.views import View
컨벤션 수정 부탁드려요!

2022-02-07 08:20 UTC, lordmyshepherd requested changes

2022-02-07 08:20 UTC, lordmyshepherd commented on julabo/settings.py
> +>>>>>>> main
해결되지 않은 컨플릭트 해결해주세요.

2022-02-07 08:20 UTC, lordmyshepherd commented on users/views.py
> +class CartView(View):
코드리뷰 내용
```python
## Cart App으로 분리
class CartView(View):
    @login_decorator
    def post(self, request):
        user = request.user
        try:  
            data = json.loads(request.body)  
            product_id = data['product_id']
            quantity   = data['quantity']

            cart, is_created = Cart.objects.get_or_create(
                user_id    = user.id,
                product_id = product_id
            )

            cart.quantity = quantity
            cart.save()

            return JsonResponse({'message': '등록성공'}, status=200)

        except KeyError:
            return JsonResponse({'message': 'key_error'}, status=400)
        
        except User.DoesNotExist:
            return JsonResponse({'message': 'User id Does Not Exist'}, status=400)

        except ObjectDoesNotExist:
            return JsonResponse({'message': 'Product id Does Not Exist'}, status=400)

    @login_decorator
    def get(self, request):
        user = request.user

        try:
            carts = Cart.objects.filter(user_id=user_id)
            results = [{
                'product_name' : cart.product.name,
                'quantity'     : cart.quantity,
                'price'        : cart.product.price * cart.quantity,
                'subcategory'  : cart.product.categorysubcategory.subcategory.name,
                'size'         : cart.product.ml
            } for cart in carts]

            total_price = 0

            for result in results:
                total_price += result['item_price']

            return JsonResponse({
                'results': results, 
                'total_price': total_price, 
                'order_date': order_date
            }, status=200)

        except User.DoesNotExist:
            return JsonResponse({'message': 'User id Does Not Exist'}, status=400)



    @login_decorator
    def delete(self, request, cart_id):
        # DELETE carts/1
        # DELETE carts?ids=[1, 2, 3, 4]
        Cart.objects.filter(user_id=request.user.id, cart_id=cart_id).delete()
        return JsonResponse({'message': 'NO_CONTENT'}, status=204)
```

2022-02-09 01:48 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-02-09 01:48 UTC, merged