[29기 최형택] 데코레이터 추가
wecode-bootcamp-korea/29-1st-JU-LABO-backend pull request #11
Opened 2022-02-04 04:34 UTC by knuckles6974

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 페이지이동시 토큰사용을 위해 데코레이터기능을 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 데코레이터에대해 조금 알게되었습니다 

<br />

## :: 기타 질문 및 특이 사항

2022-02-04 04:52 UTC, cch0807 reviewed
확인했습니다!

2022-02-04 04:52 UTC, cch0807 commented on users/utils.py
> +            payload = jwt.decode(access_token, SECRET_KEY, algorithms=[ALGORITHM])
[] 빼주세요!

2022-02-04 04:53 UTC, jiyeon-kim-ds commented on users/utils.py
> +            payload = jwt.decode(access_token, SECRET_KEY, algorithms=[ALGORITHM])
`algorithms=ALGORITHM` 으로 수정이 필요해보입니다.

2022-02-07 07:54 UTC, lordmyshepherd requested changes

2022-02-07 07:54 UTC, lordmyshepherd commented on users/utils.py
> +            return JsonResponse ({'message' : 'UNAUTHORIZED'}, status=401)
불필요한 로직은 지워주세요.

2022-02-07 07:54 UTC, lordmyshepherd commented on users/utils.py
> +from my_settings                import SECRET_KEY,ALGORITHM
```suggestion
from django.conf                import settings
```

2022-02-08 09:22 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-02-08 09:29 UTC, merged