[29기 김지연] 상품 정보 인덱스 수정
wecode-bootcamp-korea/29-1st-JU-LABO-backend pull request #12
Opened 2022-02-07 04:21 UTC by jiyeon-kim-ds

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 상세 페이지 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품 리스트에서 선택한 상품이 상품 그룹 리스트에서 가장 먼저 나오도록 수정

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 프론트엔드와의 많은 상의가 필요함을 느끼고 더 많이 소통해야겠다고 깨달앗습니다.

## :: 기타 질문 및 특이 사항

2022-02-07 07:22 UTC, cch0807 reviewed
확인했습니다~!

2022-02-09 01:56 UTC, lordmyshepherd requested changes

2022-02-09 01:56 UTC, lordmyshepherd commented on products/views.py
> +        products        = product.union(other_products)
지연님!
여기서 `product와 같은 그룹에 있는 상품들 같이 반환해주는 건가요?
그렇다면 union은 왜 다시 해주는건가요?

2022-02-09 04:55 UTC, jiyeon-kim-ds commented on products/views.py
> +        products        = product.union(other_products)
같은 그룹에 있는 상품들을 반환해주는 용도입니다! 클릭한 상품이 먼저 나올 수 있도록 나머지 상품들을 union으로 합쳤습니다.

2022-02-09 05:25 UTC, lordmyshepherd requested changes

2022-02-09 05:25 UTC, lordmyshepherd commented on products/views.py
> +        products        = product.union(other_products)
반환해주는 데이터 구조를 수정할 필요가 있어 보입니다.
우선 Client에서 product_id = 1인 상품 정보를 요청했으면, 1번 상품이 root query로 반환되어야 합니다. 아래 json 구조를 참고해주세요~
```json
{
    "id" : product.id,
    "name" : product.name,
    "related_products" : [
        {
              "id" : product.id,
              "name" : product.name,
         },
        {
              "id" : product.id,
              "name" : product.name,
         },
    ]
}
```

```suggestion
        product = Product.objects.get(id=product_id)
        related_products  = Product.objects.filter(productgroup_id=productgroup_id).exclude(id=product_id)
        related_product.insert(0, product)
```

2022-02-09 09:17 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-02-09 09:17 UTC, merged