[최창현] 상품 타입(ml) 필터 기능 추가
wecode-bootcamp-korea/29-1st-JU-LABO-backend pull request #13
Opened 2022-02-07 06:42 UTC by cch0807

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [] 리뷰 반영
- [ ] 리팩토링
- [x] 기능 추가
- [ ] 버그 수정
- [] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 리스트를 타입(ml)으로 필터할 수 있다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. ml을 통해 상품 리스트를 필터
2. 쿼리 파라미터를 통해 type의 정보를 받는다.
3. 조건문을 사용해  type필터의 사용여부를 확인한다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 프론트엔드와의 많은 상의가 필요함을 느끼고 더 많이 소통해야겠다고 깨달앗습니다.

## :: 기타 질문 및 특이 사항

2022-02-07 09:40 UTC, cch0807 commented
다시 수정해서 푸쉬 했습니다!

2022-02-08 00:53 UTC, cch0807 commented
해당 브랜치 코드 질문하고 싶은것이 생겼습니다 ! 이따 찾아뵐게요!

2022-02-08 01:48 UTC, lordmyshepherd requested changes

2022-02-08 01:48 UTC, lordmyshepherd commented on categories/views.py
>  class ProductListView(View):
code review
```python
class ProductListView(View):
  def get(self,request):
    try:
      category_subcategory_id = request.GET.get('category_subcategory_id', None)
      type_ml                 = request.GET.get('ml', None)
      image                   = Image.objects.all()
      
      filter_set = {
        "categorysubcategory__id" : category_subcategory_id,
        "ml" = type_ml,
      }

      products = Product.objects.filter(**filter_set)

      results = [{   
        'id'             : product.id,
        'name'           : product.name,
        'ml'             : product.ml,
        'price'          : product.price,
        'productgroup_id': product.productgroup.id,
        'image'          : [img for img in image.filter(product_id = product.id).values('image_url')],
        'subcategory': {
          'subcategory_id'  : product.categorysubcategory.subcategory.id,
          'subcategory_name': product.categorysubcategory.subcategory.name
        }
      } for product in products]

      return JsonResponse({'products': results}, status= 200)

    except:
      return JsonResponse({'message': 'KEY_ERROR'}, status=400) 
```

2022-02-08 01:48 UTC, lordmyshepherd commented on products/views.py
> +        'image'          : [img for img in image.filter(product_id = product.id).values('image_url')],
image를 불러올 때, Image.objects.all()이 아니라 product. 부터 시작해서 가져올 수 있도록 수정해주세요~

```suggestion
        'images' : [ for image in product....]
```

2022-02-08 01:48 UTC, lordmyshepherd commented on products/views.py
> +      return JsonResponse({'message': 'KEY_ERROR'}, status=400)
명확하게 error를 핸들링해주셔야 합니다. 단순히 except만 사용하는 경우는 피해주세요~
```suggestion
    except KeyError:
      return JsonResponse({'message': 'KEY_ERROR'}, status=400) 
```

2022-02-08 09:29 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-02-08 09:34 UTC, merged