[29기 김지연] 상품 상세 페이지 API 작업
wecode-bootcamp-korea/29-1st-JU-LABO-backend pull request #4
Opened 2022-01-27 07:11 UTC by jiyeon-kim-ds

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 상세 페이지에 데이터베이스 내용을 전달하는 API 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 임의로 설정한 `productgroup_id=2`에 해당하는 상품 정보를 json 형태로 프론트엔드에 전달
- 상품의 기본적인 정보들을 전달하고 사용자가 상품의 옵션을 선택할 수 있게 용량(ml)과 가격을 따로 전달함

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 테이블 간 정참조, 역참조에 대해 잘 알지 못하는 걸 깨닫고 더 공부할 예정입니다.
- 처음 프론트엔드로 데이터를 전달해보고 전달하는 데이터의 형태를 많이 상의해보고 (API 문서화 등을 통해) 알려야 한다는 것을 알았습니다. 

<br />

## :: 기타 질문 및 특이 사항

2022-01-27 08:52 UTC, lordmyshepherd requested changes

2022-01-27 08:52 UTC, lordmyshepherd commented on products/views.py
> +            return JsonResponse({'message': 'fail'}, status=400)
`ProductDetailView`는 상품 데이터 한개를 리턴해주는 엔드포인트 입니다.
하지만, 로직은 상품 정보 목록을 반환하도록 되어 있습니다.

피드백 1. 만들고 싶은 엔드포인트가 `ProductGroupView`인지 `ProductView`인지를 잘 고민해보시면 좋을 것 같아요.
피드백 2. 1번이 정해졌으면, client로부터 `product_id`를 받아서 product 정보를 반환할지, productgroup_id를 받아서 product_group을 반환할지 생각해보셔야 합니다.

2022-01-27 09:03 UTC, jiyeon-kim-ds commented on products/views.py
> +            return JsonResponse({'message': 'fail'}, status=400)
병민님 피드백 감사합니다! 말씀하신 내용을 바탕으로 프론트엔드와 상의한 결과 `product_id`에 따라 `ProductView`를 작성하는 것이 맞다고 결론을 내렸습니다.😀

2022-02-04 04:29 UTC, cch0807 reviewed
확인했습니다!

2022-02-04 05:41 UTC, merged