Feature/category
wecode-bootcamp-korea/29-1st-JU-LABO-backend pull request #5
Opened 2022-01-27 07:28 UTC by cch0807

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
네비게이션에서 카테고리를 선택하여 원하는 상품을 찾을 수 있다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 메인 카테고리를 선택할 시 서브 카테고리를 출력한다.
- 서브카테고리를 선택할 시 메인카테고리와 서브카테고리 속성을 가진 제품들을 출력한다.
- 출력 내용은 상품 이름 , 용량 , 가격, 상품 서브카테고리의 이름이다.
- 통신방법은 get이며 path 를 통해 category_id와 usbcategory_id 값을 입력받는다.
- 테스트 방법 :  httpi를 통해 확인 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- path parameter를 통해 get요청을 구현하는 방법을 알게되었습니다.
- foreignkey를 통한 역참조에대한 이해가 부족했는데 많은 공부를 하였습니다.

<br />

## :: 기타 질문 및 특이 사항
- 카테고리를 통한 상품 검색시 path parameter를 사용하는게 좋을지 query parameter를 사용하는게 좋을지 궁금합니다.

2022-01-27 08:24 UTC, lordmyshepherd requested changes

2022-01-27 08:24 UTC, lordmyshepherd commented on categories/views.py
> +      return JsonResponse({'message': 'KEY_ERROR'}, status=400)
1. get method 내에서 Key Error가 발생할 수 있는 경우가 없는데, Key Error 처리주고 있습니다. 불필요한 코드는 지워주세요.
2. 데이터를 반환해주실 때, 데이터를 대표하는 id 값도 같이 반환해주세요.!
```suggestion
    try:
      sub_categories = [{
          "id" : sub_category.id, 
          "name" : sub_category.name
      } for sub_category in SubCategory.objects.all()]
      
      return JsonResponse({'sub_categories': sub_categories}, status=200)
```

2022-01-27 08:24 UTC, lordmyshepherd commented on categories/views.py
> +class SubCategoryView(View):
현재 PR에 Category 호출하는 기능, SubCategory를 호출하는 기능, ... 등 전부 하나로 합쳐져 있습니다.
기능별로 PR을 분리해서 올려주셔야 합니다.

그 이유는 PR을 분리하지 않고 올리게 되면  Category 기능은 완벽해서 merge해도 문제가 없는 상황인데, SubCategory의 수정사항 때문에 동시에 전체적으로 완료되지 못하는 문제가 생깁니다.

2022-01-27 08:24 UTC, lordmyshepherd commented on categories/views.py
> +class SubCategoryView(View):
SubCategoryView는 새로운 PR로 올려주세요~

2022-01-27 08:24 UTC, lordmyshepherd commented on categories/views.py
> +class TypeView(View):
TypeView도 마찬가지 입니다~

2022-01-27 08:51 UTC, cch0807 commented on categories/views.py
> +class SubCategoryView(View):
확인했습니다!

2022-01-27 08:51 UTC, cch0807 commented on categories/views.py
> +      return JsonResponse({'message': 'KEY_ERROR'}, status=400)
확인했습니다!

2022-01-27 08:52 UTC, cch0807 commented on categories/views.py
> +class TypeView(View):
확인했습니다!

2022-01-27 08:53 UTC, cch0807 commented
수정 완료했고 서브 카테고리 뷰 따로 올리겠습니다!

2022-01-27 10:45 UTC, lordmyshepherd commented
피드백 반영이 잘 안된 것 같습니다.
아래 file change 확인해주세요~~
https://github.com/wecode-bootcamp-korea/29-1st-JU-LABO-backend/pull/5/files

2022-01-27 15:46 UTC, cch0807 commented
제가 이해를 제대로 못했었습니다! 다시 수정해서 올렸습니다!

2022-01-28 02:11 UTC, lordmyshepherd requested changes

2022-01-28 02:11 UTC, lordmyshepherd commented on categories/views.py
> +    return JsonResponse({'sub_categories': sub_categories}, status=200)
마지막 리뷰 남겨드려요~
1. 목록(list)를 반환하는 경우에는 class 명을 `CategoryListView` 혹은 `CategoriesView`로 만들어주세요.
2. Category View인데 sub_category 정보를 반환하고 있습니다. CategoryView class는 Category를 반환해야 합니다.

2022-01-28 04:32 UTC, cch0807 commented on categories/views.py
> +    return JsonResponse({'sub_categories': sub_categories}, status=200)
1. class 명을 SubCategoiresView로 수정하였습니다!
2. branch 명을 처음부터 잘못 생각해서 정한것같습니다 ㅠㅠ branch이름 수정이 필요하다면 말씀 부탁드립니다!!

2022-01-28 06:08 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-01-28 06:09 UTC, merged