[최창현] Sub_Category 기능 구현
wecode-bootcamp-korea/29-1st-JU-LABO-backend pull request #6
Opened 2022-01-27 08:56 UTC by cch0807

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
서브카테고리를 선택할 시 메인카테고리와 서브카테고리 속성을 가진 제품들을 출력한다.
출력 내용은 상품 이름 , 용량 , 가격, 상품 서브카테고리의 이름이다.
통신방법은 get이며 path 를 통해 category_id와 usbcategory_id 값을 입력받는다.
테스트 방법 : httpi를 통해 확인

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
path parameter를 통해 get요청을 구현하는 방법을 알게되었습니다.
foreignkey를 통한 역참조에대한 이해가 부족했는데 많은 공부를 하였습니다.

<br />

## :: 기타 질문 및 특이 사항
카테고리를 통한 상품 검색시 path parameter를 사용하는게 좋을지 query parameter를 사용하는게 좋을지 궁금합니다.

2022-01-27 10:46 UTC, lordmyshepherd requested changes

2022-01-27 10:46 UTC, lordmyshepherd commented on categories/views.py
> +class CategoryView(View):
여기도 SubCategory 이외에 코드는 지워주세요~

2022-01-27 15:20 UTC, cchlion commented on categories/views.py
> +class CategoryView(View):
수정하였습니다!

2022-01-28 02:27 UTC, lordmyshepherd requested changes

2022-01-28 02:27 UTC, lordmyshepherd commented on categories/views.py
> +class SubCategoryView(View):
앞 PR에서 드린 피드백과 동일하게, 목록을 반환하는 VIew는 class명을 ListView로 만들어주세요~!

2022-01-28 02:27 UTC, lordmyshepherd commented on categories/views.py
> +  def get(self,request):
함수의 `input`과 `output`을 Restful하게 다시 정의해야 될 것 같습니다.

1. 중간테이블 이름 수정이 필요할 것 같습니다. `CategoryJoin`으로 되어 있는데, 중간테이블 이름은 CategorySubCategory 이렇게 테이블을 붙여서 만드는게 컨벤션입니다.
2. 함수의 목적을 다시 고민해주세요.
    - 모든 서브 카테고리를 반환할 것 인지
    - category_id를 받아서 해당 카테고리에 속한 서브 카테고리만 반환할 것 인지
    - 힌트는 subcategory_id를 받을 필요가 없습니다. (subcategory_id를 받는 경우는 sub_category 하나만 반환할 때 사용합니다.)
2. 반환해야되는 output을 다시 정의해주세요. SubCategoriesView를 만드는거라면 sub_category 정보가 메인이 되어야 합니다.

```python
result = [{
        'id' : sub_category.id
        'name' : sub_category.name,
        'category' : {
            'id' : category.id
        }
]
```

2022-01-28 04:26 UTC, cch0807 commented on categories/views.py
> +  def get(self,request):
1. 중간 테이블 이름 수정하였습니다!
2. 함수의 목적은 category 속성과 subcategory속성을 만족하는 product를 반환하는 것이기때문에
result를 목적에 맞게 수정하였습니다!
3.반환해야 되는 output을 productlist라는 이름으로 바꾸었습니다!
4. view 이름도 목적에 맞게 ProductListView로 수정하였습니다! ( + urls.py)

2022-01-28 06:44 UTC, lordmyshepherd requested changes

2022-01-28 06:44 UTC, lordmyshepherd commented on categories/views.py
> +
```python
products = Product.objects.filter(category_subcategory___id = category_subcategory_id)

results = [{
    "id" : product.id,
    "category" : {
        "id" : product. categorysubcategory.category.id,
        "name" : product. categorysubcategory.category.name
     },
} for product in products]
```

2022-01-28 08:58 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-01-28 08:58 UTC, merged