[29기 최형택] users 수정
wecode-bootcamp-korea/29-1st-JU-LABO-backend pull request #9
Opened 2022-01-31 03:17 UTC by knuckles6974

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 깔끔한 코드를 위한 화이트 스페이스 삭제

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- merge 를 함부로 하면 안된다는것을 확인

<br />

## :: 기타 질문 및 특이 사항

2022-02-04 05:47 UTC, jiyeon-kim-ds commented on users/views.py
>              if bcrypt.checkpw(data['password'].encode('utf-8'), user.password.encode('utf-8')):
패스워드가 틀린 경우의 에러메세지가 따로 필요해보입니다.

2022-02-07 06:18 UTC, jiyeon-kim-ds requested changes

2022-02-07 06:18 UTC, jiyeon-kim-ds commented on users/views.py
> +            return JsonResponse({'message':'SUCCESS','token':token}, status=201)
여기선 데이터베이스에 리소스가 추가된 게 아니어서 status code로 200번이 더 적절해보입니다.

2022-02-07 07:55 UTC, lordmyshepherd requested changes

2022-02-07 07:55 UTC, lordmyshepherd commented on users/utils.py
> +    return wrapper
코드만 지워주세요.

2022-02-08 09:20 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-02-08 09:21 UTC, merged